### PR TITLE
prevent preview loss of resolution from original image

### PR DESCRIPTION
**Pull request by AdrienMrl**

### CODE REVIEW

**Comment by kirill3333** [comment]
@Sevauk thank you for your PR, can you provide test image, please?

**Comment by Sevauk** [comment]
Any image was experiencing a resolution loss for the preview, since the preview was generated from the canvas size, not the original image size. I can elaborate and provide illustrations here if you want.

**Comment by cinkagan** [comment]
You are right @AdrienMrl. Congratulations

**Comment by cinkagan** [comment]
You are right @AdrienMrl. Congratulations

**Pull request closed without merging**
